### ISSUE TITLE
Multiple Ports

### ISSUE THREAD

**Issue by arqbyte** [sammwyy/Lure#1]
Hi,

Is it possible to check multiple ports on one servers and show offline MOTD?

**Comment by sammwyy** [comment]
It's not a good idea. What can be done is use IPTables to write a rule that forwards all ports to the server port (eg 25565).

The client in the initial connection (handshake) sends the port with which it is connected. It can be done that if it is not equal to port 25565 or the one you want then show the offline MoTD.

**Comment by arqbyte** [comment]
I own a free/paid hosting service, and I want to show the Offline MOTD to let people know where the server is hosted. Do you have any ideas?

**Comment by arqbyte** [comment]
Please Reply
